import type {
  RecruitCrmCandidateCustomField,
  CandidateDetail,
  RecruitCrmSearchResponse,
} from "../src/recruitcrm/types.js";

export const sampleSearchResponse: RecruitCrmSearchResponse = {
  current_page: 2,
  next_page_url: "https://api.recruitcrm.io/v1/candidates/search?page=3",
  data: [
    {
      slug: "010011",
      first_name: "Michael",
      last_name: "Scott",
      email: "mscott@gmail.com",
      contact_number: "+1123226666",
      position: "Software Developer",
      current_organization: "Dunder Mifflin",
      current_status: "Employed",
      status_label: "Unavailable",
      city: "New York",
      state: "New York",
      country: "United States",
      work_ex_year: 2,
      updated_on: "2020-06-29T05:36:22.000000Z",
      relevant_experience: 2,
      specialization: "Computer Science",
      skill: "Java,Python",
      language_skills: "English(Native/Bilingual Proficiency)",
      notice_period: 60,
      available_from: "2020-06-29T05:36:22.000000Z",
      willing_to_relocate: 1,
      current_salary: 150000,
      salary_expectation: 180000,
      salary_type: {
        id: "1",
        label: "Monthly Salary",
      },
      currency_id: 2,
      linkedin: "http://www.linkedin.com/michael4",
      github: "",
      candidate_summary: "Regional manager turned engineer.",
      owner: 10001,
    },
  ],
};

export const sampleCandidateCustomFieldsResponse: RecruitCrmCandidateCustomField[] = [
  {
    field_id: 34,
    entity_type: "candidate",
    field_type: "multiselect",
    field_name: "Tech Stack",
    default_value: "Python,Java,XYZ",
  },
  {
    field_id: 38,
    entity_type: "candidate",
    field_type: "dropdown",
    field_name: "Category",
    default_value: "Sciences,Finance,Operations",
  },
  {
    field_id: 80,
    entity_type: "candidate",
    field_type: "file",
    field_name: "Branded CV",
    default_value: "",
  },
  {
    field_id: 88,
    entity_type: "candidate",
    field_type: "checkbox",
    field_name: "Enrichment",
    default_value: "",
  },
  {
    field_id: 55,
    entity_type: "candidate",
    field_type: "company",
    field_name: "Referred by",
    default_value: "",
  },
  {
    field_id: 7,
    entity_type: "candidate",
    field_type: "date_time",
    field_name: "Yop Date 2026",
    default_value: "",
  },
];

export const sampleCandidateDetailResponse: CandidateDetail = {
  id: 45134,
  first_name: "Saurav",
  last_name: "Jordan",
  email: "saurav.j@cc.com",
  contact_number: "",
  gender_id: 0,
  qualification_id: 0,
  specialization: "",
  work_ex_year: 0,
  candidate_dob: null,
  current_salary: 0,
  salary_expectation: 0,
  resume: null,
  willing_to_relocate: 0,
  current_organization: "",
  current_status: "",
  notice_period: 0,
  currency_id: 59,
  slug: "17755473509460000453mHh",
  profile_update_link_status: 0,
  profile_update_requested_on: null,
  profile_updated_on: "2026-04-07T07:35:50.000000Z",
  avatar: null,
  facebook: "",
  twitter: "",
  linkedin: "",
  github: "",
  xing: "",
  created_on: "2026-04-07T07:35:50.000000Z",
  updated_on: "2026-04-07T07:35:50.000000Z",
  city: "",
  locality: "",
  state: "",
  country: "",
  address: "",
  relevant_experience: 0,
  position: "",
  available_from: null,
  salary_type: {
    id: "2",
    label: "Annual Salary",
  },
  source: "Talent Pool",
  language_skills: "",
  skill: "",
  custom_fields: [
    {
      field_id: 34,
      entity_type: "candidate",
      field_name: "Tech Stack",
      field_type: "multiselect",
      value: "",
    },
    {
      field_id: 88,
      entity_type: "candidate",
      field_name: "Enrichment",
      field_type: "checkbox",
      value: "0",
    },
    {
      field_id: 80,
      entity_type: "candidate",
      field_name: "Branded CV",
      field_type: "file",
      value: null,
    },
  ],
  created_by: 0,
  updated_by: 0,
  owner: 453,
  resource_url: "https://app.recruitcrm.io/candidate/17755473509460000453mHh",
  is_email_opted_out: "false",
  email_opt_out_source: null,
  candidate_summary: "<p>Saurav Jordan</p>",
  work_history: [
    {
      candidate_id: 32870618,
      id: 115908566,
      title: "Власник компанії",
      work_company_name: "TATfood",
      employment_type: 0,
      industry_id: 0,
      work_location: "",
      salary: 0,
      is_currently_working: 1,
      work_start_date: 1527854400,
      work_end_date: 0,
      work_description:
        "Киев, Украина * Рекрутинг/підбір технологів харчової промилосвості на постійну роботу та проекти в Україні та за кордон",
    },
    {
      candidate_id: 32870618,
      id: 115908567,
      title: "голова відділу розвитку продажів харчових інгредієнтів/Head of sales of food department",
      work_company_name: "Azelis",
      employment_type: 0,
      industry_id: 0,
      work_location: "",
      salary: 0,
      is_currently_working: 0,
      work_start_date: 1325419200,
      work_end_date: 1509537600,
      work_description: "Киев, Украина",
    },
  ],
  education_history: [
    {
      candidate_id: 32870618,
      id: 43505871,
      institute_name: "National University of Food Technologies",
      educational_qualification: "Postgraduate Degree",
      educational_specialization: "Food Technology and Processing",
      grade: "",
      education_location: "",
      education_start_date: 1696118400,
      education_end_date: 1817078400,
      education_description: "",
    },
  ],
  current_organization_slug: null,
  last_calllog_added_on: null,
  last_calllog_added_by: null,
  last_email_sent_on: null,
  last_email_sent_by: null,
  last_sms_sent_on: null,
  last_sms_sent_by: null,
  last_meeting_created_on: null,
  last_meeting_created_by: null,
  last_linkedin_message_sent_on: null,
  last_linkedin_message_sent_by: null,
  last_communication: null,
  postal_code: "",
  off_limit_status_id: null,
  status_label: null,
  off_limit_reason: null,
  off_limit_end_date: null,
};
