import type {
  RecruitCrmCandidateCustomField,
  RecruitCrmCandidateJobAssignmentHiringStageHistoryResponse,
  RecruitCrmCallLogSearchResponse,
  CandidateDetail,
  CompanyDetail,
  ContactDetail,
  CreatedHotlist,
  CreatedNote,
  CreatedTask,
  JobDetail,
  RecruitCrmHiringPipelineResponse,
  RecruitCrmJobAssignedCandidatesResponse,
  RecruitCrmCompanySearchResponse,
  RecruitCrmContactSearchResponse,
  RecruitCrmHotlistSearchResponse,
  RecruitCrmJobSearchResponse,
  RecruitCrmMeetingSearchResponse,
  RecruitCrmNoteSearchResponse,
  RecruitCrmNoteTypeListResponse,
  RecruitCrmSearchResponse,
  RecruitCrmTaskSearchResponse,
  RecruitCrmTaskTypeListResponse,
  RecruitCrmUserListResponse,
} from "../src/recruitcrm/types.js";

export const sampleSearchResponse: RecruitCrmSearchResponse = {
  current_page: 2,
  next_page_url: "https://api.recruitcrm.io/v1/candidates/search?page=3",
  data: [
    {
      slug: "010011",
      first_name: "Sample",
      last_name: "Candidate",
      email: "sample.candidate@example.com",
      contact_number: "+1-555-0100",
      position: "Software Developer",
      current_organization: "Acme Labs",
      current_status: "Employed",
      status_label: "Unavailable",
      city: "Example City",
      state: "Example State",
      country: "Example Country",
      work_ex_year: 2,
      updated_on: "2020-06-29T05:36:22.000000Z",
      relevant_experience: 2,
      specialization: "Computer Science",
      skill: "Java,Python",
      language_skills: "English(Native/Bilingual Proficiency)",
      notice_period: 60,
      available_from: "2020-06-29T05:36:22.000000Z",
      willing_to_relocate: 1,
      current_salary: 150000,
      salary_expectation: 180000,
      salary_type: {
        id: "1",
        label: "Monthly Salary",
      },
      currency_id: 2,
      linkedin: "https://www.example.com/in/sample-candidate",
      github: "",
      candidate_summary: "Sample candidate summary.",
      owner: 10001,
    },
  ],
};

export const sampleJobAssignedCandidatesResponse: RecruitCrmJobAssignedCandidatesResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/jobs/job-sample-001/assigned-candidates?page=2",
  data: [
    {
      stage_date: "2026-02-20T09:08:45.000000Z",
      status: {
        status_id: "8",
        label: "Placed",
      },
      candidate: {
        slug: "candidate-assigned-sample-001",
        first_name: "Michael",
        last_name: "Scott",
        email: "mscott@example.com",
        contact_number: "+1-555-0105",
        avatar: "https://api.recruitcrm.io/v1/candidates/candidate-assigned-sample-001/avatar/sample",
        current_organization: "Dunder Mifflin",
        current_status: "Employed",
        city: "Scranton",
        country: "United States",
        updated_on: "2026-02-21T10:00:00.000000Z",
        position: "Regional Manager",
        current_salary: 150000,
        salary_expectation: 180000,
        linkedin: "https://www.linkedin.com/in/michael-scott",
        custom_fields: [
          {
            field_id: 1,
            value: "Region 1",
            entity_type: "candidate",
            field_name: "Region",
            field_type: "text",
          },
        ],
        resource_url: "https://app.recruitcrm.io/candidate/candidate-assigned-sample-001",
        is_email_opted_out: true,
        email_opt_out_source: "Manually opted out",
      },
    },
  ],
};

export const sampleHiringPipelineResponse: RecruitCrmHiringPipelineResponse = [
  {
    status_id: 1,
    label: "Assigned",
  },
  {
    status_id: "8",
    label: "Placed",
  },
  {
    stage_id: 10,
    label: "Applied",
  },
];

export const sampleCandidateCustomFieldsResponse: RecruitCrmCandidateCustomField[] = [
  {
    field_id: 34,
    entity_type: "candidate",
    field_type: "multiselect",
    field_name: "Tech Stack",
    default_value: "Python,Java,XYZ",
  },
  {
    field_id: 38,
    entity_type: "candidate",
    field_type: "dropdown",
    field_name: "Category",
    default_value: "Sciences,Finance,Operations",
  },
  {
    field_id: 80,
    entity_type: "candidate",
    field_type: "file",
    field_name: "Branded CV",
    default_value: "",
  },
  {
    field_id: 88,
    entity_type: "candidate",
    field_type: "checkbox",
    field_name: "Enrichment",
    default_value: "",
  },
  {
    field_id: 55,
    entity_type: "candidate",
    field_type: "company",
    field_name: "Referred by",
    default_value: "",
  },
  {
    field_id: 7,
    entity_type: "candidate",
    field_type: "date_time",
    field_name: "Yop Date 2026",
    default_value: "",
  },
];

export const sampleJobSearchResponse: RecruitCrmJobSearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/jobs/search?page=2",
  data: [
    {
      id: 313,
      slug: "job-sample-001",
      name: "Operations Analyst",
      company_slug: "company-sample-001",
      contact_slug: "contact-sample-001",
      secondary_contact_slugs: ["contact-sample-002", "", null],
      note_for_candidates: "Please bring sample documents.",
      number_of_openings: 2,
      minimum_experience: 2,
      maximum_experience: 3,
      min_annual_salary: 90000,
      max_annual_salary: 110000,
      salary_type: {
        id: "2",
        label: "Annual Salary",
      },
      job_status: {
        id: 1,
        label: "Open",
      },
      job_status_comment:
        '[{"status_id":1,"remark":"","updated_by":"Sample User","updated_on":1710853474,"status_label":"Open"}]',
      job_skill: "Data Analysis, Project Management",
      job_type: "Contract",
      pay_rate: 80,
      bill_rate: 100,
      job_category: "Operations",
      city: "Example City",
      locality: "Downtown",
      state: "Example State",
      country: "Example Country",
      created_on: "2026-04-01T09:15:00.000000Z",
      updated_on: "2026-04-07T10:30:00.000000Z",
      owner: 8772,
      enable_job_application_form: 1,
      application_form_url: "https://recruitcrm.io/apply/job-sample-001",
      contact_email: "primary.contact@example.com",
      contact_number: "+1-555-0102",
      secondary_contact_email: "secondary.contact@example.com",
      secondary_contact_number: "+1-555-0103",
      job_description_text: "<p>Large ignored description</p>",
      job_description_file: "https://files.example.com/job-description.pdf",
      job_questions: [
        {
          id: 721,
          question: "Why this role?",
        },
      ],
      custom_fields: [
        {
          field_id: 1,
          value: "Region 1",
        },
      ],
      collaborator_users: [
        {
          id: 34,
          first_name: "Sample",
          last_name: "User",
          email: "sample.user@example.com",
        },
      ],
      collaborator_teams: [null],
      xml_feeds: [null],
      resource_url: "https://app.recruitcrm.io/job/job-sample-001",
      shared_job_image: "https://app.recruitcrm.io/assets/images/default-share.png",
      targetcompanies: [
        {
          name: "Sample Target Company",
          slug: "company-sample-target-001",
        },
      ],
    },
  ],
};

export const sampleCompanySearchResponse: RecruitCrmCompanySearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/companies/search?page=2",
  data: [
    {
      id: 403,
      industry_id: 0,
      company_name: "Example Holdings",
      about_company: "Large ignored company description.",
      logo: "https://api.recruitcrm.io/v1/companies/company-sample-001/logo/example",
      slug: "company-sample-001",
      created_on: "2020-06-03T17:05:48.000000Z",
      updated_on: "2026-04-08T08:18:32.000000Z",
      website: "https://www.example-holdings.test",
      city: "",
      address: "123 Example Street",
      facebook: "https://www.example.com/example-holdings",
      twitter: null,
      linkedin: null,
      linkedin_id: null,
      custom_fields: [
        {
          field_id: 1,
          entity_type: "company",
          field_name: "Parent Organization",
          field_type: "dropdown",
          value: null,
        },
      ],
      created_by: 3735,
      updated_by: 19768,
      owner: 3735,
      resource_url: "https://app.recruitcrm.io/company/company-sample-001",
      is_child_company: "No",
      is_parent_company: "Yes",
      child_company_slugs: ["company-sample-child-001", "", null],
      parent_company_slug: null,
      locality: null,
      state: "Example State",
      country: "Example Country",
      postal_code: "10001",
      contact_slug: ["contact-sample-001", "", null, "contact-sample-002"],
      last_meeting_created_on: null,
      last_meeting_created_by: null,
      off_limit_status_id: "12",
      status_label: "Off Limits",
      off_limit_reason: "Existing exclusive agreement",
      off_limit_end_date: "2026-12-31",
    },
  ],
};

export const sampleCompanyDetailResponse: CompanyDetail = {
  ...sampleCompanySearchResponse.data[0],
  slug: "company-detail-sample-001",
  logo: "https://api.recruitcrm.io/v1/companies/company-detail-sample-001/logo/example",
  resource_url: "https://app.recruitcrm.io/company/company-detail-sample-001",
};

export const sampleContactSearchResponse: RecruitCrmContactSearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/contacts/search?page=2",
  data: [
    {
      id: 501,
      slug: "contact-sample-001",
      first_name: "Pam",
      last_name: "Beesly",
      email: "pam.beesly@example.com",
      contact_number: "+1-555-0142",
      linkedin: "https://www.linkedin.com/in/pam-beesly",
      company_slug: "company-sample-001",
      additional_company_slugs: ["company-sample-aux-001", "", null],
      designation: "Office Manager",
      city: "Scranton",
      locality: "Downtown",
      address: "1725 Slough Avenue",
      created_on: "2026-02-01T09:00:00.000000Z",
      updated_on: "2026-04-09T11:30:00.000000Z",
      custom_fields: [
        {
          field_id: 1,
          field_name: "Department",
          field_type: "dropdown",
          value: "Operations",
        },
      ],
      resource_url: "https://app.recruitcrm.io/contact/contact-sample-001",
      last_email_sent_on: "2026-04-10T09:15:00.000000Z",
      off_limit_status_id: null,
      status_label: null,
      off_limit_reason: null,
      off_limit_end_date: null,
    },
  ],
};

export const sampleContactDetailResponse: ContactDetail = {
  ...sampleContactSearchResponse.data[0],
  slug: "contact-detail-sample-001",
  owner: 3735,
  owner_name: "Sample Owner",
  company_name: "Example Holdings",
  facebook: null,
  twitter: null,
  xing: null,
  state: "Pennsylvania",
  country: "United States",
  postal_code: "18503",
  is_email_opted_out: false,
  email_opt_out_source: null,
  contact_stage_remarks: null,
  last_calllog_added_on: null,
  last_calllog_added_by: null,
  last_email_sent_by: 3735,
  last_sms_sent_on: null,
  last_sms_sent_by: null,
  last_meeting_created_on: "2026-04-08T12:00:00.000000Z",
  last_meeting_created_by: 3735,
  last_linkedin_message_sent_on: null,
  last_linkedin_message_sent_by: null,
  last_communication: "2026-04-10T09:15:00.000000Z",
  custom_fields: [
    {
      field_id: 1,
      entity_type: "contact",
      field_name: "Department",
      field_type: "dropdown",
      value: "Operations",
    },
  ],
  resource_url: "https://app.recruitcrm.io/contact/contact-detail-sample-001",
};

export const sampleHotlistSearchResponse: RecruitCrmHotlistSearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/hotlists/search?page=2",
  data: [
    {
      id: 702,
      name: "Product Leaders",
      related_to_type: "candidate",
      shared: 1,
      created_by: 66960,
      related: "candidate-sample-001, candidate-sample-002 , ,candidate-sample-003",
      ignored_field: "ignored",
    },
    {
      id: 703,
      name: "Private shortlist",
      related_to_type: "candidate",
      shared: 0,
      created_by: 68596,
      related: null,
    },
  ],
};

export const sampleCreatedHotlistResponse: CreatedHotlist = {
  id: 307309,
  name: "Product Leaders",
  related_to_type: "candidate",
  related: "",
  shared: 0,
  created_by: 453,
};

export const sampleUserListResponse: RecruitCrmUserListResponse = [
  {
    id: 453,
    first_name: "Sean",
    last_name: "Mallapurkar",
    email: "sean@example.com",
    contact_number: "+1-555-0191",
    status: "Active",
    role: "Account Owner",
    teams: [
      {
        team_id: 1435,
        team_name: "Legal Recruitment Team",
      },
      {
        team_id: "2253",
        team_name: "US Team",
      },
    ],
  },
  {
    id: "999",
    first_name: "Brandon",
    last_name: "McArthur",
    email: null,
    contact_number: "+1-555-0199",
    status: "Deactivated",
    role: null,
    teams: [],
  },
  {
    id: 3557,
    first_name: "Sarvesh",
    last_name: null,
    email: null,
    contact_number: null,
    status: "Deactivated",
    teams: null,
  },
];

export const sampleUserListResponseBareTeams: RecruitCrmUserListResponse = [
  {
    id: 101,
    first_name: "Alex",
    last_name: "Kim",
    email: "alex@example.com",
    contact_number: null,
    status: "Active",
    teams: [1435, 2253, 9871],
  },
];

export const sampleJobDetailResponse: JobDetail = {
  id: 313,
  slug: "job-detail-sample-001",
  name: "Operations Analyst",
  company_slug: "company-sample-001",
  contact_slug: "contact-sample-001",
  secondary_contact_slugs: ["contact-sample-002"],
  note_for_candidates: "Please bring sample documents.",
  number_of_openings: 2,
  minimum_experience: 2,
  maximum_experience: 3,
  min_annual_salary: 90000,
  max_annual_salary: 110000,
  salary_type: {
    id: 2,
    label: "Annual Salary",
  },
  job_status: {
    id: 1,
    label: "Open",
  },
  job_status_comment:
    '[{"status_id":1,"remark":"","updated_by":"Sample User","updated_on":1710853474,"status_label":"Open"}]',
  latitude: "40.7128",
  longitude: "-74.0060",
  city: "Example City",
  locality: "Downtown",
  state: "Example State",
  country: "Example Country",
  address: "123 Example Street",
  created_on: "2026-04-01T09:15:00.000000Z",
  created_by: 1001,
  updated_on: "2026-04-07T10:30:00.000000Z",
  updated_by: 1002,
  owner: 8772,
  enable_job_application_form: 1,
  job_posting_status: 4,
  job_code: "J10001",
  show_company_logo: 0,
  specialization: "",
  qualification_id: 4,
  currency_id: 124,
  job_description_text: "<p>Detailed sample description.</p>",
  job_description_file: "",
  application_form_url: "https://recruitcrm.io/apply/job-detail-sample-001",
  shared_job_image: "https://app.recruitcrm.io/assets/images/default-share.png",
  job_skill: "Data Analysis, Project Management",
  job_type: "Contract",
  pay_rate: 80,
  bill_rate: 100,
  job_category: "Operations",
  job_location_type: "0",
  postal_code: "10001",
  job_questions: [
    {
      id: 721,
      question: "Why this role?",
    },
  ],
  custom_fields: [
    {
      field_id: 1,
      entity_type: "job",
      field_name: "Region",
      field_type: "dropdown",
      value: "Region 1",
    },
  ],
  targetcompanies: [
    {
      name: "Sample Target Company",
      slug: "company-sample-target-001",
    },
  ],
  collaborator_users: [47462, 48322],
  collaborator_teams: [],
  xml_feeds: [
    {
      id: 1,
      type: "default",
      label: "Sample Feed",
    },
  ],
  resource_url: "https://app.recruitcrm.io/job/job-detail-sample-001",
};

export const sampleTaskSearchResponse: RecruitCrmTaskSearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/tasks/search?page=2",
  data: [
    {
      id: 2572223,
      related_to: "candidate-related-sample-001",
      task_type: null,
      related_to_type: "candidate",
      related_to_name: "Sample Candidate",
      description: "",
      title: "Follow up",
      status: 1,
      start_date: "2021-11-19T08:30:00.000000Z",
      reminder_date: "2021-11-19T08:00:00.000000Z",
      reminder: 30,
      owner: 2890,
      created_on: "2021-11-12T12:02:45.000000Z",
      updated_on: "2022-11-16T18:33:57.000000Z",
      created_by: 2890,
      updated_by: 453,
      related: {
        slug: "candidate-related-sample-001",
        email: "sample.related@example.com",
        first_name: "Sample",
        last_name: "Candidate",
      },
      associated_candidates: ["candidate-related-sample-001"],
      associated_companies: [],
      associated_contacts: [],
      associated_jobs: [],
      associated_deals: [],
      collaborators: [],
      collaborator_users: [],
      collaborator_teams: [null],
    },
  ],
};

export const sampleTaskTypeListResponse: RecruitCrmTaskTypeListResponse = [
  {
    id: 332,
    label: "Follow up",
  },
  {
    id: 53794,
    label: "Interview scheduling",
  },
  {
    id: 209961,
    label: "Call Candidate",
  },
];

export const sampleCreatedTaskResponse: CreatedTask = {
  id: 66753909,
  related_to: "candidate-related-sample-001",
  task_type: {
    id: 332,
    label: "Follow up",
  },
  related_to_type: "candidate",
  related_to_name: "Sample Candidate",
  description: "<p><strong>Created by Codex</strong></p>",
  title: "Codex API test task",
  status: null,
  start_date: "2026-04-28T04:30:00.000000Z",
  reminder_date: "2026-04-28T04:00:00.000000Z",
  reminder: 30,
  owner: 453,
  created_on: "2026-04-27T12:13:47.000000Z",
  updated_on: "2026-04-27T12:13:47.000000Z",
  created_by: 453,
  updated_by: 453,
  associated_candidates: ["candidate-related-sample-001"],
  associated_companies: [],
  associated_contacts: [],
  associated_jobs: [],
  associated_deals: [],
  collaborators: [
    {
      attendee_type: "user",
      attendee_id: "12654",
      display_name: "Jane Scott",
    },
  ],
  collaborator_users: [
    {
      id: 34,
      first_name: "Jane",
      last_name: "Scott",
      email: "jane.scott@example.com",
      contact_number: "+1-555-0200",
      avatar: "https://example.com/avatar.png",
    },
  ],
  collaborator_teams: [
    1435,
    {
      team_id: 16,
      team_name: "Delivery",
    },
  ],
  related: {
    slug: "candidate-related-sample-001",
    email: "sample.related@example.com",
    contact_number: "+1-555-0101",
    first_name: "Sample",
    last_name: "Candidate",
  },
};

export const sampleMeetingSearchResponse: RecruitCrmMeetingSearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/meetings/search?page=2",
  data: [
    {
      id: 47202185,
      title: "Sample Candidate/Product Manager (Acme Labs)",
      meeting_type: {
        id: 20707,
        label: "Candidate Interview with Client",
      },
      description: "<p>Test</p>",
      address: "https://meet.example.com/sample-meeting",
      reminder: 30,
      start_date: "2025-10-31T09:30:00.000000Z",
      end_date: "2025-10-31T10:00:00.000000Z",
      related_to: "candidate-related-sample-001",
      related_to_type: "candidate",
      do_not_send_calendar_invites: 1,
      status: 0,
      reminder_date: "2025-10-31T09:00:00.000000Z",
      all_day: 1,
      owner: 69232,
      created_on: "2025-10-24T07:45:45.000000Z",
      updated_on: "2025-10-31T08:50:30.000000Z",
      created_by: 69232,
      updated_by: 69232,
      attendees: [
        {
          attendee_id: "candidate-related-sample-001",
          attendee_type: "Candidate",
          display_name: "Sample Candidate",
        },
      ],
      related: {
        slug: "candidate-related-sample-001",
        first_name: "Sample",
        last_name: "Candidate",
      },
      associated_candidates: ["candidate-related-sample-001"],
      associated_companies: [],
      associated_contacts: [],
      associated_jobs: [],
      associated_deals: [],
      collaborator_users: [],
      collaborator_teams: [],
    },
  ],
};

export const sampleNoteSearchResponse: RecruitCrmNoteSearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/notes/search?page=2",
  data: [
    {
      id: 24667666,
      note_type: {
        id: 205989,
        label: "Candidate Interaction",
      },
      description: "Sample note content",
      related_to: "candidate-related-sample-001",
      related_to_type: "candidate",
      created_on: "2024-07-30T11:10:30.000000Z",
      updated_on: "2024-07-30T11:10:30.000000Z",
      created_by: 66960,
      updated_by: 66960,
      resource_url: "https://app.recruitcrm.io/notes/24667666",
      related: {
        slug: "candidate-related-sample-001",
        first_name: "Sample",
        last_name: "Candidate",
      },
      associated_candidates: ["candidate-related-sample-001"],
      associated_companies: [],
      associated_contacts: [],
      associated_jobs: [],
      associated_deals: [],
      collaborator_users: [],
      collaborator_teams: [null],
    },
  ],
};

export const sampleNoteTypeListResponse: RecruitCrmNoteTypeListResponse = [
  {
    id: 42,
    label: "Internal Note",
  },
  {
    id: 108871,
    label: "General Note",
  },
  {
    id: 205989,
    label: "Candidate Interaction",
  },
];

export const sampleCreatedNoteResponse: CreatedNote = {
  id: 66752552,
  note_type: {
    id: 108871,
    label: "General Note",
  },
  description:
    "<p><strong>Codex rich text API test</strong></p><ul><li><em>Bold and italic formatting</em></li></ul>",
  related_to: "candidate-related-sample-001",
  related_to_type: "candidate",
  created_on: "2026-04-27T11:15:46.000000Z",
  updated_on: "2026-04-27T11:15:46.000000Z",
  created_by: 453,
  updated_by: 453,
  associated_candidates: ["candidate-related-sample-001", "candidate-related-sample-002"],
  associated_companies: [],
  associated_contacts: [],
  associated_jobs: [],
  associated_deals: [],
  collaborator_users: [
    {
      id: 34,
      first_name: "Jane",
      last_name: "Scott",
      email: "jane.scott@example.com",
      contact_number: "+1-555-0200",
      avatar: "https://example.com/avatar.png",
    },
  ],
  collaborator_teams: [
    1435,
    {
      team_id: 16,
      team_name: "Delivery",
    },
  ],
  related: {
    slug: "candidate-related-sample-001",
    first_name: "Sample",
    last_name: "Candidate",
    email: "sample.related@example.com",
    contact_number: "+1-555-0101",
  },
};

export const sampleCallLogSearchResponse: RecruitCrmCallLogSearchResponse = {
  current_page: 1,
  next_page_url: "https://api.recruitcrm.io/v1/call-logs/search?page=2",
  data: [
    {
      id: 498645,
      call_type: "CALL_OUTGOING",
      custom_call_type: {
        id: 2,
        label: "Pitch Attempt",
      },
      call_started_on: "2022-03-10T17:16:43.000000Z",
      contact_number: "+1-555-0101",
      call_notes: "",
      duration: 17,
      related_to: "candidate-related-sample-001",
      related_to_type: "candidate",
      created_on: "2022-03-10T17:16:43.000000Z",
      updated_on: "2022-03-10T17:17:20.000000Z",
      created_by: 8772,
      updated_by: 8772,
      related: {
        slug: "candidate-related-sample-001",
        first_name: "Sample",
        last_name: "Candidate",
      },
      associated_candidates: ["candidate-related-sample-001"],
      associated_companies: [],
      associated_contacts: [],
      associated_jobs: [],
      associated_deals: [],
      collaborator_users: [],
      collaborator_teams: [null],
    },
  ],
};

export const sampleCandidateJobAssignmentHiringStageHistoryResponse: RecruitCrmCandidateJobAssignmentHiringStageHistoryResponse =
  [
    {
      job_slug: "16540132164740000453lqF",
      job_name: "Chief of Staff",
      company_slug: "7063184",
      company_name: "Google",
      job_status_id: 1,
      job_status_label: "Open",
      candidate_status_id: 231169,
      candidate_status: "1st Interview",
      remark: "great profile",
      updated_by: 0,
      updated_on: "2025-02-27T14:53:15.000000Z",
    },
    {
      job_slug: "17331412929920063396kmG",
      job_name: "Pool for XYZ client",
      company_slug: "16868200767130002890hdW",
      company_name: "Apple",
      job_status_id: "1",
      job_status_label: "Open",
      candidate_status_id: 503354,
      candidate_status: "Phone Screen",
      remark: "",
      updated_by: "453",
      updated_on: "2025-02-28T13:26:04.000000Z",
    },
    {
      job_slug: "16540132164740000453lqF",
      job_name: "Chief of Staff",
      company_slug: "7063184",
      company_name: "Google",
      job_status_id: 1,
      job_status_label: "Open",
      candidate_status_id: 364508,
      candidate_status: null,
      remark: "great candidate",
      updated_by: 0,
      updated_on: "2024-12-02T15:14:51.000000Z",
    },
  ];

export const sampleCandidateDetailResponse: CandidateDetail = {
  id: 45134,
  first_name: "Sample",
  last_name: "Profile",
  email: "sample.profile@example.com",
  contact_number: "",
  gender_id: 0,
  qualification_id: 0,
  specialization: "",
  work_ex_year: 0,
  candidate_dob: null,
  current_salary: 0,
  salary_expectation: 0,
  resume: {
    filename: "Sample Resume.pdf",
    file_link: "https://api.recruitcrm.io/v1/candidates/candidate-detail-sample-001/resume/example",
  },
  willing_to_relocate: 0,
  current_organization: "",
  current_status: "",
  notice_period: 0,
  currency_id: 59,
  slug: "candidate-detail-sample-001",
  profile_update_link_status: 0,
  profile_update_requested_on: null,
  profile_updated_on: "2026-04-07T07:35:50.000000Z",
  avatar: null,
  facebook: "",
  twitter: "",
  linkedin: "",
  github: "",
  xing: "",
  created_on: "2026-04-07T07:35:50.000000Z",
  updated_on: "2026-04-07T07:35:50.000000Z",
  city: "",
  locality: "",
  state: "",
  country: "",
  address: "",
  relevant_experience: 0,
  position: "",
  available_from: null,
  salary_type: {
    id: "2",
    label: "Annual Salary",
  },
  source: "Talent Pool",
  language_skills: "",
  skill: "",
  custom_fields: [
    {
      field_id: 34,
      entity_type: "candidate",
      field_name: "Tech Stack",
      field_type: "multiselect",
      value: "",
    },
    {
      field_id: 88,
      entity_type: "candidate",
      field_name: "Enrichment",
      field_type: "checkbox",
      value: "0",
    },
    {
      field_id: 80,
      entity_type: "candidate",
      field_name: "Branded CV",
      field_type: "file",
      value: null,
    },
  ],
  created_by: 0,
  updated_by: 0,
  owner: 453,
  resource_url: "https://app.recruitcrm.io/candidate/candidate-detail-sample-001",
  is_email_opted_out: "false",
  email_opt_out_source: null,
  candidate_summary: "<p>Sample Profile</p>",
  work_history: [
    {
      candidate_id: 32870618,
      id: 115908566,
      title: "Founder",
      work_company_name: "Acme Foods",
      employment_type: 0,
      industry_id: 0,
      work_location: "",
      salary: 0,
      is_currently_working: 1,
      work_start_date: 1527854400,
      work_end_date: 0,
      work_description: "Built hiring workflows for food manufacturing teams.",
    },
    {
      candidate_id: 32870618,
      id: 115908567,
      title: "Head of Sales",
      work_company_name: "Northwind Ingredients",
      employment_type: 0,
      industry_id: 0,
      work_location: "",
      salary: 0,
      is_currently_working: 0,
      work_start_date: 1325419200,
      work_end_date: 1509537600,
      work_description: "Led regional sales operations.",
    },
  ],
  education_history: [
    {
      candidate_id: 32870618,
      id: 43505871,
      institute_name: "Example Institute of Technology",
      educational_qualification: "Postgraduate Degree",
      educational_specialization: "Food Technology and Processing",
      grade: "",
      education_location: "",
      education_start_date: 1696118400,
      education_end_date: 1817078400,
      education_description: "",
    },
  ],
  current_organization_slug: null,
  last_calllog_added_on: null,
  last_calllog_added_by: null,
  last_email_sent_on: null,
  last_email_sent_by: null,
  last_sms_sent_on: null,
  last_sms_sent_by: null,
  last_meeting_created_on: null,
  last_meeting_created_by: null,
  last_linkedin_message_sent_on: null,
  last_linkedin_message_sent_by: null,
  last_communication: null,
  postal_code: "",
  off_limit_status_id: null,
  status_label: null,
  off_limit_reason: null,
  off_limit_end_date: null,
};
